### ISSUE TITLE
Steps for remote radius server 

### ISSUE THREAD

**Issue by wstdenis** [deajan/pfSense-cp-auth-onestep#1]
Do you by chance have a few steps to integrate this into an external radius server? It would be so helpful.

**Comment by deajan** [comment]
Actually you have to configure pfSense's captive portal to use an external radius server.
The wrapper I wrote just creates a radius user account via MySQL.
As long as your radius runs with MySQL, setting the right database config in captive-portal.php should be sufficient.

**Comment by wstdenis** [comment]
Okay great! I see that setting I will give that a shot. Will this setup work with the DNS forwarder, or does the DNS resolver need to be running.

**Comment by deajan** [comment]
AFAIK, the DNS resolver needs to run on pfSense in order to redirect to the captive portal.
