### ISSUE TITLE
Radius Error on form submit

### ISSUE THREAD

**Issue by Milo-81** [deajan/pfSense-cp-auth-onestep#7]
Hi, i think there is a problem with the database insert.
When i click to the connect button, the registration form is back
In the system log of pfsense i can see this error : 
(6) Invalid user (sql1 : Failed to create the pair: Invalid vendor name in attribute name "Password"): [toto@gmail.com] (from client tester port 2000 cli xx:xx:xx:xx:xx:xx) 
where xx is the mac address 
And in the user database nothin is recorded 

I use pfsense 2.4.3 so maybe your script isn't compatible.

**Comment by Milo-81** [comment]
After research i juste find what is wrong in the code.
In the ozy-captive.php on the line 281 
`if (!$statement = $db->prepare("INSERT INTO radcheck (username, attribute,  value) VALUES (?, 'Password', ?)"))`

The password value is wrong, now, freeradius use Cleartext-Password. And now freeradius use the value := in the op column.

So i replace this line by 
`if (!$statement = $db->prepare("INSERT INTO radcheck (username, attribute, op, value) VALUES (?, 'Cleartext-Password', ':=', ?)"))`

and it's work !

**Comment by deajan** [comment]
Thank you for your help.
Did you have to modify anything else ? Also, what FreeRADIUS version do you run so I can update the script to run with newer pfSense builds.

**Comment by Milo-81** [comment]
No i dont have modify anything else.
For FreeRadius, I use the freeradius3-3.0.17 version.

And after some checks, i think it will be better to modify the sql script to change the attribute and op default value than the php script itself ;) 
![capture](https://user-images.githubusercontent.com/42843715/46391580-fa0c9200-c6dd-11e8-92cc-63bdbdf489f7.PNG)

**Comment by deajan** [comment]
Thank you. I will update the docs accordingly.
